### ISSUE TITLE
Trainer Modal

### ISSUE THREAD

**Issue by Empyrxvn** [Stacktrek-Training/stack-sched#1]
@rieza-ix 
Add message that indicates trainer was added successfully.

**Comment by riezxcvii** [comment]
Done
Commit 7e763d5 [rieza-ix](https://github.com/Stacktrek-Training/stack-sched/commits?author=rieza-ix) [add: successful message after adding a trainer in the form](https://github.com/Stacktrek-Training/stack-sched/commit/7e763d55dd0f115b37cddf37e03a6c097667480d)
