### ISSUE TITLE
Too long lines of code

### ISSUE THREAD

**Issue by Eliasfate** [Stacktrek-Training/stack-sched#7]
ButtonsTrainerTable.tsx - Too long singular lines of code maybe break into paragraph-like forms

**Comment by riezxcvii** [comment]
@Eliasfate , check this commit 6a89e58b586efa71a9bdb70f0f5fa2367d3dad51. I already formatted the document using Prettier ESLint suggested by Ma'am Joy.
Kindly close the issue if you have no suggestions to make.
Thank you.
